### PR TITLE
define & upgrade maven-jar-plugin version

### PR DESCRIPTION
**Pull request by hboutemy**
fixes Reproducible Builds: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/cognite/units/units-catalog/README.md

notice that creating a Git tag on release would be useful

### CODE REVIEW

**Review by matiascognite — APPROVED** [review]
LGTM

**Comment by matiascognite** [comment]
Hmm... do we need to bump the version for this?

**Comment by hboutemy** [comment]
yes, you need, and it's a general best practice

**Comment by hboutemy** [comment]
> do we need to bump the version for this?

if by "bump the version" you mean change the version **of units-catalog**, no: this does not change anything from library users

**Pull request merged**
